### ISSUE TITLE
Wrong version range for fabric mod

### ISSUE THREAD

**Issue by axd1x8a** [wendall911/ReadyPlayerFun#13]
```
Mod 'Ready Player Fun' (readyplayerfun) 1.19-1.19.2-2.4.1.14-FABRIC requires version 1.19,1.19.1,1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
```

**Comment by wendall911** [comment]
Ok, fabric does a horrible job of documenting the version range. Maybe someday they will support proper version strings. I'll fix this and push a fix in the morning. Thanks for reporting.

**Comment by wendall911** [comment]
Ok, released on Modrinth and Curseforge. Let me know if you have any issues. I changed it to pin to 1.19.2 for now.

**Comment by axd1x8a** [comment]
Yes, it's working now, thank you very much
