### ISSUE TITLE
Redundant

### ISSUE THREAD

**Issue by NDM1574** [wendall911/ReadyPlayerFun#16]
This mod no longer requires updating, along with Tick Stasis. This feature is available in the base game as of 1.21.2 and has more customization.

**Comment by wendall911** [comment]
Oh, that's great, can you provide more details?

**Comment by wendall911** [comment]
I see! pause-when-empty-seconds Awesome.

**Comment by NDM1574** [comment]
It really is a great new feature, but thank you for bringing it to older versions and having it before the game itself, it's a big achievement to do something that Mojang implements themselves later on.

**Comment by wendall911** [comment]
It's funny, but this was super obvious to do earlier. The latest code changes are pretty amazing, and good for Minecraft's future. New engineering manager at Mojang is excellent. It is just bizarre that this stuff wasn't done a long time ago. I bet they were patching their own servers to do this.

**Comment by wendall911** [comment]
I just updated so users can keep track of server pause duration and display message on first join. I'll keep this mod around for a bit, as it is leveraged mostly by server ops folks.
