### ISSUE TITLE
Gamerule randomTickSpeed does not change back after player login. (1.12.2)

### ISSUE THREAD

**Issue by MickgClone** [wendall911/ReadyPlayerFun#9]
This is my first time submitting an issue to github so sorry if I miss anything.
So, after installing the mod, I realized my trees stopped growing. 
I'm pretty sure this is the mod that's doing it cause it pauses time. So, I think that's the connection between the mod and the issue. 
I had a hard time figuring out why and I realized on logout that the gamerule "randomTickSpeed" would be set to 0 but not be reset after player login. 
For all I know this could be just something else messing with the mod but I don't want to have to search through all the mods to fix the problem so I just set up something that will reset the gamerule when a player logs in.
If the issue actually isn't this mod, then I'm sorry for wasting your time but I do think this mod is not setting it back.
The modpack I'm using is "MC Eternal".
(If the mod doesn't change the gamerule, please close this while stating that. Sorry and thanks!)

**Comment by DaddyP1G** [comment]
had to remove mod for same reason.  Forge version 1.18.2

**Comment by wendall911** [comment]
> had to remove mod for same reason. Forge version 1.18.2

The latest release solves this issue.

**Comment by wendall911** [comment]
This is actually fixed now. I was able to reproduce. Will not fix for 1.12.x, as I'm not entirely sure that I can with that version.
